// IEProtectMode.idl : IDL source for IEProtectMode
//

// This file will be processed by the MIDL tool to
// produce the type library (IEProtectMode.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(26513D64-4506-4960-B960-634C9E11D893),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IStockBar : IDispatch{
};
[
	uuid(4D020EA4-F056-48BF-A04B-5D889BE378F1),
	version(1.0),
]
library IEProtectModeLib
{
	importlib("stdole2.tlb");
	[
		uuid(D468F21D-499B-4771-9878-66DF76CED414)		
	]
	coclass StockBar
	{
		[default] interface IStockBar;
	};
};

